icommons_tools/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^icommons_ui/', include('icommons_ui.urls')),
    url(r'^canvas_whitelist/', include('canvas_whitelist.urls', namespace="cwl")),
    url(r'^course_conclusion/', include('course_conclusion.urls', namespace='cc')),
    url(r'^course_selection/', include('course_selection.urls', namespace="cs")),
    url(r'^isites_export/', include('isites_export_tool.urls', namespace="et")),
    url(r'^not_authorized/', 'icommons_ui.views.not_authorized', name="not_authorized"),
    url(r'^pin/', include('icommons_common.auth.urls', namespace="pin")),
    url(r'^qualtrics_taker_auth/', include('qualtrics_taker_auth.urls', namespace="qta")),
    url(r'^qualtrics_whitelist/', include('qualtrics_whitelist.urls', namespace="qwl")),
    url(r'^shopping/', include('canvas_shopping.urls', namespace="sh")),
    url(r'^term_tool/', include('term_tool.urls', namespace="tt")),
]

term_tool/urls.py
from django.conf.urls import patterns, include, url

from term_tool.views import (
    ExcludeCoursesFromViewing,
    SchoolListView,
    TermCreateView,
    TermEditView,
    TermListView,
    exclude_courses,
)


urlpatterns = patterns('',
    url(r'^$', SchoolListView.as_view(), name='schoollist'),
    url(r'^(?P<school_id>\w+)/term_list/$', TermListView.as_view(),
        name='termlist'),
    url(r'^term/(?P<pk>\d+)/edit$', TermEditView.as_view(), name='termedit'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses$',
        exclude_courses, name='excludecourses'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses/data$',
        ExcludeCoursesFromViewing.as_view(), name='excludecoursesdata'),
    url(r'^term/new/(?P<school_id>\w+)$', TermCreateView.as_view(),
        name='termcreate'),

)

term_tool/forms.py
from datetime import datetime, time, date
import logging

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Submit, Button
from crispy_forms.bootstrap import FormActions
from icommons_common.models import Term, TermCode, School

from util import util


logger = logging.getLogger(__name__)


class EditTermForm(forms.ModelForm):

    # this is a model form that's mostly automatically generated; here we specify that it should be based on the Term model:
    class Meta:
        model = Term
        exclude = ('user_id',)

    # make the school, term_code and academic_year fields hidden; they should not be changed once the term is created
    school = forms.ModelChoiceField(queryset=School.objects.all(), widget=forms.widgets.HiddenInput())
    term_code = forms.ModelChoiceField(queryset=TermCode.objects.all(), widget=forms.widgets.HiddenInput())
    academic_year = forms.IntegerField(widget=forms.widgets.HiddenInput())
    source = forms.CharField(required=False, widget=forms.widgets.HiddenInput())
    hucc_academic_year = forms.IntegerField(required=False, widget=forms.widgets.HiddenInput())

    # make the calendar_year hidden - it should not be directly editable (is determined based on start_date)
    calendar_year = forms.IntegerField(required=False, widget=forms.widgets.HiddenInput())

    # hide user_id and modified_on fields, they should not be directlty editable

    user_id = forms.CharField(required=False, widget=forms.widgets.HiddenInput())

    # make some additional fields required; they're not strictly required in the database, but we want them to be required here
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True, help_text='The last day of the term, including exam period')

    xreg_available = forms.BooleanField(required=False, label='Cross-registration is available for this term. Uncheck this box if <b>none</b> of the courses in this term are available for cross-registration')
    xreg_start_date = forms.DateField(required=False, label='Cross-reg start date', help_text='Cross-registration starts at the <b>beginning</b> of the day specified.')
    xreg_end_date = forms.DateField(required=False, label='Cross-reg end date', help_text='Cross-registration ends at the <b>end</b> of the day specified.')

    active = forms.BooleanField(required=False, label='Active for Course iSites')
    shopping_active = forms.BooleanField(required=False, help_text='If your school does not have a shopping period, you can ignore this setting.')
    include_in_catalog = forms.BooleanField(required=False, label='Include this term in the <b>production</b> Course Catalog')
    include_in_preview = forms.BooleanField(required=False, label='Include this term in the <b>preview</b> Course Catalog')
    enrollment_end_date = forms.DateField(required=False, help_text='The last day students can enroll in courses in this term')
    drop_date = forms.DateField(required=False, help_text='Last day students can drop the course')
    withdrawal_date = forms.DateField(required=False, help_text='The last day students can withdraw from courses in this term')
    shopping_end_date = forms.DateField(required=False, help_text='If your school does not have a shopping period, you can ignore this setting.')
    exam_start_date = forms.DateField(required=False)
    exam_end_date = forms.DateField(required=False)
    conclude_date = forms.DateField(required=False, help_text='If set, courses and enrollments will be marked as "concluded" in Canvas after this date. The course content will be available in read-only mode.')
    catalog_note = forms.CharField(required=False, widget=forms.Textarea, label='notes')

    def __init__(self, *args, **kwargs):
        super(EditTermForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.help_text_inline = True
        self.helper.render_unmentioned_fields = True
        self.helper.form_error_title = u"There were problems with the information you submitted."
        self.helper.layout = Layout(
            Field('academic_year'),
            Field('calendar_year'),
            Field('hucc_academic_year'),
            Field('term_code'),
            Field('school'),
            Field('display_name'),
            Field('start_date'),
            Field('end_date'),
            Field('active'),
            Field('shopping_active'),
            Fieldset(
                'Cross-registration and Catalog',
                'xreg_available',
                'xreg_start_date', 'xreg_end_date',
                'include_in_catalog', 'include_in_preview',
            ),
            Fieldset(
                'Other Dates',
                'conclude_date',
                'shopping_end_date',
                'enrollment_end_date',
                'drop_date',
                'withdrawal_date',
                'exam_start_date',
                'exam_end_date',
            ),
            Field('user_id'),
            Field('catalog_note'),
            FormActions(
                Submit('save', 'Save changes'),
                Button('cancel', 'Cancel')
            ),
        )

    """
    override the clean method so that we can perform custom validation; this is done at the form level because some validation
    rules depend on the values of multiple fields.
    """
    def clean(self):

        cleaned_data = super(EditTermForm, self).clean()

        school = cleaned_data.get('school')
        logger.info("clean starting for %s" % school)
        term_code = cleaned_data.get('term_code')
        academic_year = cleaned_data.get('academic_year')
        calendar_year = cleaned_data.get('calendar_year')
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        xreg_available = cleaned_data.get('xreg_available')
        xreg_start_date = cleaned_data.get('xreg_start_date')
        xreg_end_date = cleaned_data.get('xreg_end_date')
        display_name = cleaned_data.get('display_name')
        hucc_academic_year = cleaned_data.get('hucc_academic_year')
        shopping_end_date = cleaned_data.get('shopping_end_date')
        enrollment_end_date = cleaned_data.get('enrollment_end_date')
        drop_date = cleaned_data.get('drop_date')
        withdrawal_date = cleaned_data.get('withdrawal_date')
        exam_start_date = cleaned_data.get('exam_start_date')
        exam_end_date = cleaned_data.get('exam_end_date')
        source = cleaned_data.get('source')

        '''
        decrypt user_id to insert into database
        '''
        encoded = cleaned_data.get('user_id')
        cleaned_data['user_id'] = util.decrypt_string(encoded)

        # default the display_name if it's not set
        if display_name is None or display_name == '':
            cleaned_data['display_name'] = '{0} {1}'.format(term_code.term_name, academic_year)

        # make sure that the start date is before the end date
        if start_date and end_date and start_date > end_date:
            self._errors['start_date'] = self.error_class([''])
            self._errors['end_date'] = self.error_class([''])
            raise forms.ValidationError("The start date must be before the end date.")

        # make sure that the interval between the start date and end date is less than one year
        if start_date and end_date and (end_date.toordinal() - start_date.toordinal()) > 365:
            self._errors['start_date'] = self.error_class([''])
            self._errors['end_date'] = self.error_class([''])
            raise forms.ValidationError("The start date and end date cannot be more than one year apart.")

        if not school.school_id == 'sum' and not school.school_id == 'ext':
            if xreg_available is True:
                if (xreg_start_date is None or xreg_start_date == ''):
                    self._errors['xreg_start_date'] = self.error_class([''])
                    raise forms.ValidationError("The cross-reg start date field cannot be empty.")

                if (xreg_end_date is None or xreg_end_date == ''):
                    self._errors['xreg_end_date'] = self.error_class([''])
                    raise forms.ValidationError("The cross-reg end date field cannot be empty.")


            '''
            There was a request to remove the validation check below. This check validated
            that the start and end dates for cross reg were between the start and end dates of the term.
            If this is reinstated it needs to be indented to fall in line with the if block above.
            Alternativly you could add a check for xreg_end_date in the if block below and indent out.
            '''
            # make sure that the xreg end date is between the term start and end
            #if xreg_end_date > end_date or xreg_end_date < start_date:
            #    logger.warn("xreg_end_date outside of term start/end")
            #    self._errors['xreg_start_date'] = self.error_class([''])
            #    raise forms.ValidationError("The cross-reg end date must be between the term start and end dates.")

        # make sure that the xreg start date is before the xreg end date
        if xreg_start_date and xreg_end_date and xreg_start_date > xreg_end_date:
            self._errors['xreg_start_date'] = self.error_class([''])
            self._errors['xreg_end_date'] = self.error_class([''])
            raise forms.ValidationError("The cross-reg start date must be before the cross-reg end date.")

        # make sure that the interval between the xreg_start date and xreg_end date is less than one year
        if xreg_start_date and xreg_end_date and (xreg_end_date.toordinal() - xreg_start_date.toordinal()) > 365:
            logger.warn("xreg_interval too greater than one year")

term_tool/templates/term_tool/base.html
{% extends "icommons_ui/base.html" %}

{% block tool_title %}Term Tool{% endblock tool_title %}

term_tool/templates/term_tool/exclude_courses.html
{% extends "term_tool/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block stylesheet %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="//cdn.datatables.net/1.10.6/css/jquery.dataTables.css">
{% endblock %}

{% block page_title %}Disable the all authorized parameter for a course{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url "tt:schoollist" %}">Schools</a></li>
    <li><a href="{% url "tt:termlist" school_id %}">{{ school_id|upper }} Terms</a></li>
    <li class="active"><a href="#">Edit Term {{ term_id }}</a></li>
</ul>
{% endblock %}


{% block content %}

    <div id="messages" class="alert alert-success alert-dismissible hidden fade in" role="alert">
        <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div id="messages-text" class="alert-text"></div>
    </div>
    <div id="errors" class="alert alert-danger alert-dismissible hidden fade in" role="alert">
        <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div id="errors-text" class="alert-text"></div>
    </div>

    <table id="course-list-table" class="display" cellspacing="0" width="100%">
    </table>


{% endblock content %}

    {% block javascript %}
{{ block.super }}
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.6/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){

        function updateAlertsWithJsonResponse(json) {
            $.each(json, function(key, value){
                var $alertDiv = (key == 'success') ? $("#messages") : $("#errors");
                $alertDiv.find('.alert-text').append('<p>' + value + '</p>');
                $alertDiv.removeClass('hidden');
            });
        }

        function handleExcludeCourse(event) {
            var $checkbox = $(event.target);
            var state = $checkbox.prop('checked') ? 'true' : 'false';
            var value = $checkbox.attr('value');
            var url = "{% url 'tt:excludecoursesdata' term_id school_id %}";
            var ajax_req = $.ajax({
                url: url,
                type: "POST",
                dataType: "json",
                data: {
                    'state' : state,
                    'course_instance_id' : value,
                    'csrfmiddlewaretoken' : '{{ csrf_token }}'
                }
            }).done(function(json) {
                updateAlertsWithJsonResponse(json);
            }).fail(function(jqXHR) {
                updateAlertsWithJsonResponse(jqXHR.responseJSON);
            });
        }

        $('.close').on('click', function() {
            $(this).parent().addClass('hidden');
            $(this).siblings('.alert-text').empty()
        });

        $('#course-list-table').DataTable({
            ajax: "{% url 'tt:excludecoursesdata' term_id school_id %}",
            columns: [
                {name: 'course_instance_id', title: 'Course Instance ID'},
                {name: 'short_title', title: 'Short Title'},
                {name: 'title', title: 'Title'},
                {
                    name: 'exclude_from_shopping',
                    render: function (data, type, row, meta) {
                        return '<input type="checkbox" name="exclude_from_shopping" value="'
                                   + row[0] + '" id="input-course-instance-'
                                   + row[0] + '" class="checkboxinput checkbox"'
                                   + (data ? ' checked="checked"' : '')
                                   + '>';
                    },
                    title: 'Disable auth user access',
                },
            ],

            drawCallback: function(){
                $('#course-list-table .checkbox').on('click', handleExcludeCourse);
            },
            serverSide: true,
            preDrawCallback: function(){
                $('#course-list-table .checkbox').off('click', handleExcludeCourse);
            },
            processing: true,
        });
    })
    </script>
{% endblock %}

term_tool/templates/term_tool/school_list.html
{% extends "term_tool/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}Choose a School{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
	<li class="active"><a href="#">Schools</a></li>
</ul>
{% endblock %}


{% block content %}
{% if school_list %}
<div class="page-header">
    <h1>Choose a school</h1>
</div>

<table class="table">
	{% for school in school_list %}
		<tr><td>{{ school.school_id|upper }}</td><td><a href="{% url "tt:termlist" school_id=school.school_id %}"> {{ school.title_short }}</a></td></tr>
	{% endfor %}
</table>

{% endif %}


{% endblock content %}

term_tool/templates/term_tool/term_create.html
{% extends "term_tool/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}Create New {{ school.school_id|upper }} Term{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url "tt:schoollist" %}">Schools</a></li>
    <li><a href="{% url "tt:termlist" school_id=school.school_id%}">{{ school.school_id|upper }} Terms</a></li>
    <li class="active"><a href="#">New Term</a></li>
</ul>
{% endblock %}


{% block content %}

{% crispy form %}

<p>
    * required
</p>

{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
    $(document).ready(function(){
        if ( $('#id_school').val() != 'colgsas' ) {
            $('#div_id_shopping_active').hide();
            $('#div_id_shopping_end_date').hide();
            $('#id_user_id').val('{{USERID}}');
        }
        
        if ( $('#id_school').val() != 'ext' && $('#id_school').val() != 'sum') {
            var xreg_start = $('#div_id_xreg_start_date label').html().trim();
            var xreg_end = $('#div_id_xreg_end_date label').html().trim();
            xreg_start += '*';
            xreg_end += '*';
            $('#div_id_xreg_start_date label').html(xreg_start);
            $('#div_id_xreg_end_date label').html(xreg_end);
        }

        $('.dateinput').datepicker({format: 'yyyy-mm-dd'})

    });
</script>
{% endblock javascript %}

term_tool/templates/term_tool/term_edit.html
{% extends "term_tool/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}Edit Term {{ term.term_id }}{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url "tt:schoollist" %}">Schools</a></li>
    <li><a href="{% url "tt:termlist" school_id=object.school_id%}">{{ object.school_id|upper }} Terms</a></li>
    <li class="active"><a href="#">Edit Term {{ term.term_id }}</a></li>
</ul>
{% endblock %}

{% block content %}

<h3>{{ term.school_id|upper }} / Academic year {{ term.academic_year }} / Term code {{ term.term_code.term_code }} ({{ term.term_code }})
</h3>

    <br />

{% crispy form %}

<p>
    * required
</p>

{% endblock %}

{% block javascript %}
{{ block.super }}
<script>
    $(document).ready(function(){

        $('#button-id-cancel').click(function(){
            parent.history.back();
            return false;
        });

        if ( $('#id_school').val() != 'ext' && $('#id_school').val() != 'sum') {
            var xreg_start = $('#div_id_xreg_start_date label').html().trim();
            var xreg_end = $('#div_id_xreg_end_date label').html().trim();
            xreg_start += '*';
            xreg_end += '*';
            $('#div_id_xreg_start_date label').html(xreg_start);
            $('#div_id_xreg_end_date label').html(xreg_end);
        }

        $('.dateinput').datepicker({format: 'yyyy-mm-dd'})
    });
</script>
{% endblock %}

term_tool/templates/term_tool/term_list.html
{% extends "term_tool/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}{{ school.school_id|upper }} Terms{% endblock %}


{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url "tt:schoollist" %}">Schools</a></li>
    <li class="active"><a href="#">{{ school.school_id|upper }} Terms</a></li>
</ul>
{% endblock %}


{% block content %}

{% if AUTHORIZEDTOEDIT %}
    <a href="{% url "tt:termcreate" school_id=school.school_id %}" class="btn btn-success">
        <i class="icon-plus"></i> Create a new {{ school.school_id|upper }} term</a>
{% endif %}

{% if term_list %}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Display Name</th>
            <th>Academic Year</th>
            {% comment "Temporarily hiding this feature" %}
            <th>Disable Auth User Param</th>
            {% endcomment %}
            <th>Start Date</th>
            <th>End Date</th>
            <th>Xreg Start Date</th>
            <th>Xreg End Date</th>
        </tr>
    </thead>
    <tbody>
    {% for term in term_list %}

        {% if school.school_id == 'sum' or school.school_id == 'ext' or term.xreg_available == 0 %}
            {% if term.start_date == None or term.end_date == None %}
                <tr class="error">
            {% else %}
                <tr>
            {% endif %}

        {% else %}
            {% if term.start_date == None or term.end_date == None or term.xreg_start_date == None or term.xreg_end_date == None %}
                <tr class="error">
            {% else %}
                <tr>
            {% endif %}
        {% endif %}

        {% if AUTHORIZEDTOEDIT %}
                <td>
                    <a href="{% url "tt:termedit" pk=term.term_id %}">{{ term.display_name|default:term.term_id }}</a>
                </td>
        {% else %}
                <td>
                    {{ term.display_name|default:term.term_id }}
                </td>
        {% endif %}


            <td>
                {{ term.academic_year }}
            </td>

            {% comment "Temporarily hiding this feature" %}
            <td>
                {% if term.shopping_active and AUTHORIZEDTOEDIT %}
                    <a href="{% url "tt:excludecourses" term_id=term.term_id school_id=school.school_id %}">update courses</a>
                {% else %}
                    update courses
                {% endif %}
            </td>
            {% endcomment %}

            <td>
                {% if term.start_date == None %}<span class="label label-danger"><i class="fa fa-exclamation-triangle"></i></span>{% endif %}
                {{ term.start_date|date }}
            </td>
            <td>
                {% if term.end_date == None %}<span class="label label-danger"><i class="fa fa-exclamation-triangle"></i></span>{% endif %}
                {{ term.end_date|date }}
            </td>

            {% if school.school_id == 'sum' or school.school_id == 'ext' or term.xreg_available == 0 %}
                <td>
                    <span class="label label-default">n/a</span>
                    {{ term.xreg_start_date|date }}
                </td>
                <td>
                    <span class="label label-default">n/a</span>
                    {{ term.xreg_end_date|date }}
                </td>
            {% else %}
                <td>
                    {% if term.xreg_start_date == None %}<span class="label label-danger"><i class="fa fa-exclamation-triangle"></i></span>{% endif %}
                    {{ term.xreg_start_date|date }}
                </td>
                <td>
                    {% if term.xreg_end_date == None %}<span class="label label-danger"><i class="fa fa-exclamation-triangle"></i></span>{% endif %}
                    {{ term.xreg_end_date|date }}
                </td>
            {% endif %}


        </tr>
    {% endfor %}
    </tbody>

</table>



{% endif %}

    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}"> <i class="fa fa-chevron-left"></i> </a></li>
        {% else %}
        <li class="disabled"><a href="#"> <i class="fa fa-chevron-left"></i> </a></li>
        {% endif %}

        {% for page_num in paginator.page_range %}
        <li {% if page_num == page_obj.number%} class="active" {% endif %}>
            <a href="?page={{ page_num }}">{{ page_num }}</a>
        </li>

        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}"> <i class="fa fa-chevron-right"></i> </a></li>
        {% else %}
            <li class="disabled"><a href="#"> <i class="fa fa-chevron-right"></i> </a></li>
        {% endif %}

    </ul>


{% endblock content %}