bulk_course_settings/urls.py
from django.urls import path, re_path

from bulk_course_settings.views import (

    BulkSettingsListView, BulkSettingsCreateView, BulkSettingsRevertView, BulkSettingsDetailView
)

urlpatterns = [
    path('', BulkSettingsListView.as_view(), name='job_list'),
    path('create_new_job/', BulkSettingsCreateView.as_view(), name='create_new_job'),
    re_path(r'^revert_setting/(?P<school_id>[a-z]{3,7})/(?P<job_id>[0-9]{1,10})/', BulkSettingsRevertView.as_view(), name='revert_setting'),
    re_path(r'^job_detail/(?P<job_id>[0-9]{1,10})/', BulkSettingsDetailView.as_view(), name='job_detail'),
]

canvas_account_admin_tools/urls.py
import watchman.views
from django.conf import settings
from django.urls import include, path, re_path
from icommons_ui import views as icommons_ui_views

from canvas_account_admin_tools import views

urlpatterns = [
    path('account_dashboard', views.dashboard_account, name='dashboard_account'),
    path('bulk_enrollment_tool/', include(('bulk_enrollment_tool.urls', 'bulk_enrollment_tool'), namespace='bulk_enrollment_tool')),
    path('canvas_site_creator/', include(('canvas_site_creator.urls', 'canvas_site_creator'), namespace='canvas_site_creator')),
    path('course_info/', include(('course_info.urls', 'course_info'), namespace='course_info')),
    path('course_info_v2/', include(('course_info_v2.urls', 'course_info_v2'), namespace='course_info_v2')),
    path('cross_list_courses/', include(('cross_list_courses.urls', 'cross_list_courses'), namespace='cross_list_courses')),
    re_path(r'^icommons_rest_api/(?P<path>.*)/', views.icommons_rest_api_proxy, name='icommons_rest_api_proxy'),
    path('lti_auth_error', icommons_ui_views.not_authorized, name='lti_auth_error'),
    path('lti_launch', views.lti_launch, name='lti_launch'),
    path('not_authorized', icommons_ui_views.not_authorized, name='not_authorized'),
    path('people_tool/', include(('people_tool.urls', 'people_tool'), namespace='people_tool')),
    path('publish_courses/', include(('publish_courses.urls', 'publish_courses'), namespace='publish_courses')),
    path('bulk_course_settings/', include(('bulk_course_settings.urls', 'bulk_course_settings'), namespace='bulk_course_settings')),
    path('canvas_site_deletion/', include(('canvas_site_deletion.urls', 'canvas_site_deletion'), namespace='canvas_site_deletion')),
    path('masquerade_tool/', include(('masquerade_tool.urls', 'masquerade_tool'), namespace='masquerade_tool')),
    path('self_enrollment_tool/', include(('self_enrollment_tool.urls', 'self_enrollment_tool'), namespace='self_enrollment_tool')),
    path('self_unenrollment_tool/', include(('self_unenrollment_tool.urls', 'self_unenrollment_tool'), namespace='self_unenrollment_tool')),
    path('bulk_site_creator/', include(('bulk_site_creator.urls', 'bulk_site_creator'), namespace='bulk_site_creator')),
    path('tool_config/', views.tool_config, name='tool_config'),
    path('w/', include('watchman.urls')),
    re_path(r'^status/?$', watchman.views.bare_status),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass  # This is OK for a deployed instance running in DEBUG mode

icommons_tools/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^icommons_ui/', include('icommons_ui.urls')),
    url(r'^canvas_whitelist/', include('canvas_whitelist.urls', namespace="cwl")),
    url(r'^course_conclusion/', include('course_conclusion.urls', namespace='cc')),
    url(r'^course_selection/', include('course_selection.urls', namespace="cs")),
    url(r'^isites_export/', include('isites_export_tool.urls', namespace="et")),
    url(r'^not_authorized/', 'icommons_ui.views.not_authorized', name="not_authorized"),
    url(r'^pin/', include('icommons_common.auth.urls', namespace="pin")),
    url(r'^qualtrics_taker_auth/', include('qualtrics_taker_auth.urls', namespace="qta")),
    url(r'^qualtrics_whitelist/', include('qualtrics_whitelist.urls', namespace="qwl")),
    url(r'^shopping/', include('canvas_shopping.urls', namespace="sh")),
    url(r'^term_tool/', include('term_tool.urls', namespace="tt")),
]

term_tool/urls.py
from django.conf.urls import patterns, include, url

from term_tool.views import (
    ExcludeCoursesFromViewing,
    SchoolListView,
    TermCreateView,
    TermEditView,
    TermListView,
    exclude_courses,
)


urlpatterns = patterns('',
    url(r'^$', SchoolListView.as_view(), name='schoollist'),
    url(r'^(?P<school_id>\w+)/term_list/$', TermListView.as_view(),
        name='termlist'),
    url(r'^term/(?P<pk>\d+)/edit$', TermEditView.as_view(), name='termedit'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses$',
        exclude_courses, name='excludecourses'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses/data$',
        ExcludeCoursesFromViewing.as_view(), name='excludecoursesdata'),
    url(r'^term/new/(?P<school_id>\w+)$', TermCreateView.as_view(),
        name='termcreate'),

)

bulk_course_settings/models.py
import logging
from django.db import models
from django.urls import reverse

from coursemanager.models import Term

from bulk_course_settings import constants


logger = logging.getLogger(__name__)


class Job(models.Model):
    """
    Master table to manage bulk changes to course settings
    """

    DESIRED_SETTING_CHOICES = (
        ('True', 'True'),
        ('False', 'False')
    )

    SETTINGS_TO_MODIFY_CHOICES = (
        ('is_public', 'Course is open to the public'),
        ('is_public_to_auth_users', 'Course is open to all authenticated users'),
        ('public_syllabus', 'Syllabus is open to the public'),
        ('public_syllabus_to_auth', 'Syllabus is open to all authenticated users')
    )

    WORKFLOW_STATUS = (
        (constants.NEW, 'New'),
        (constants.QUEUED, 'Queued'),
        (constants.IN_PROGRESS, 'In progress'),
        (constants.COMPLETED_SUCCESS, 'Completed successfully'),
        (constants.COMPLETED_ERRORS, 'Completed with errors'),
        (constants.FAILED, 'Failed')
    )

    school_id = models.CharField(max_length=10)
    term_id = models.IntegerField(null=True, blank=True)
    meta_term_id = models.CharField(max_length=50, null=True, blank=True)
    term_name = models.CharField(max_length=1000, null=True, blank=True)
    setting_to_be_modified = models.CharField(max_length=50, choices=SETTINGS_TO_MODIFY_CHOICES, default='is_public')
    desired_setting = models.CharField(max_length=50, choices=DESIRED_SETTING_CHOICES, default='True')
    workflow_status = models.CharField(max_length=20, choices=WORKFLOW_STATUS, default=constants.NEW)
    related_job_id = models.IntegerField(null=True)
    created_by = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def get_term_name(self):
        term = Term.objects.get(term_id=int(self.term_id))
        return term.display_name


class Details(models.Model):
    """
    Details for each bulk course settings job run
    """

    WORKFLOW_STATUS = (
        (constants.NEW, 'New'),
        (constants.SKIPPED, 'Skipped'),
        (constants.COMPLETED, 'Completed'),
        (constants.FAILED, 'Failed')
    )

    parent_job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='details')
    canvas_course_id = models.IntegerField(null=True, blank=True)
    current_setting_value = models.CharField(max_length=20, null=True, blank=True)
    prior_state = models.CharField(max_length=2000, null=True)
    post_state = models.CharField(max_length=2000, null=True)
    workflow_status = models.CharField(max_length=20, choices=WORKFLOW_STATUS, default=constants.NEW)
    is_modified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

bulk_course_settings/views.py
import logging
from typing import Dict, List

from coursemanager.models import CourseInstance, Term
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Q
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from harvardkey_cas.mixins import LoginRequiredMixin
from lti_school_permissions.mixins import LTIPermissionRequiredMixin
from rest_framework.exceptions import ValidationError as DRFValidationError

from bulk_course_settings import constants, utils
from bulk_course_settings.forms import CreateBulkSettingsForm
from bulk_course_settings.models import Details, Job

logger = logging.getLogger(__name__)


def lti_auth_error(request):
	raise PermissionDenied


class BulkSettingsListView(LTIPermissionRequiredMixin, LoginRequiredMixin, ListView):
	"""Display a table with all Jobs created from this account."""
	model = Job
	template_name = 'bulk_course_settings/job_list.html'
	context_object_name = 'jobs'
	permission = 'bulk_course_settings'

	def get_queryset(self):
		account_sis_id = self.request.LTI['custom_canvas_account_sis_id']
		school_id = account_sis_id.split(':')[1]
		job_queryset = Job.objects.filter(school_id=school_id)

		# Annotate the Job queryset with counts for each workflow_state
		job_queryset = job_queryset.annotate(
			details_total_count=Count('details'),
			details_success_count=Count('details', filter=Q(details__workflow_status='COMPLETED')),
			details_failed_count=Count('details', filter=Q(details__workflow_status='FAILED')),
			details_skipped_count=Count('details', filter=Q(details__workflow_status='SKIPPED'))
		)

		return job_queryset


class BulkSettingsCreateView(LTIPermissionRequiredMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
	"""Displays the form used to create a Job with the desired setting and value"""
	form_class = CreateBulkSettingsForm
	template_name = 'bulk_course_settings/create_new_job.html'
	model = Job
	success_message = 'Job was created successfully.'
	permission = 'bulk_course_settings'

	def get_context_data(self, **kwargs):
		context = super(BulkSettingsCreateView, self).get_context_data(**kwargs)
		account_sis_id = self.request.LTI['custom_canvas_account_sis_id']
		context['account_sis_id'] = account_sis_id
		context['school_id'] = account_sis_id.split(':')[1]
		context['terms'] = utils.get_term_data_for_school(account_sis_id)
		return context

	def form_valid(self, form):
		"""If the form is valid, create the Job and send it to the queueing lambda"""
		lti_session = getattr(self.request, 'LTI', {})
		audit_user_id = lti_session.get('custom_canvas_user_login_id')
		account_sis_id = lti_session.get('custom_canvas_account_sis_id')
		response = super(BulkSettingsCreateView, self).form_valid(form)
		term = Term.objects.get(term_id=form.instance.term_id)
		meta_term_id = term.meta_term_id()

		form.instance.workflow_status = constants.QUEUED
		form.instance.meta_term_id = meta_term_id
		form.instance.term_name = term.display_name
		form.instance.created_by = audit_user_id

		if not all((audit_user_id, account_sis_id)):
			raise DRFValidationError(
				'Invalid LTI session: custom_canvas_user_login_id and '
				'custom_canvas_account_sis_id required.')

		sis_account_id = f'sis_account_id:{account_sis_id}'
		meta_term_id = f'sis_term_id:{meta_term_id}'

		if not all((sis_account_id, meta_term_id)):
			raise DRFValidationError('Both account and term are required.')

		job = form.instance
		job.save()

		if job.id is not None:
			job_id = job.id
		else:
			job_id = form.instance.id

		logger.info(f' Creating new Bulk course settings job with ID: {job_id}.')

		# Set other variables to be in the payload
		setting_to_be_modified = job.setting_to_be_modified
		desired_setting = job.desired_setting

		# Get a list of Canvas course ID's for a given term and account
		# Adding support for this tool to work in sub-sub accounts by checking the account_sis_id for dept or coursegroup
		if account_sis_id.startswith('school'):
			canvas_course_id_list_acct_term = (CourseInstance.objects.filter(canvas_course_id__isnull=False,
			                                                                 term=term,
			                                                                 course__school=account_sis_id.removeprefix('school:'))
			                                   .values_list('canvas_course_id', flat=True)).distinct()
		elif account_sis_id.startswith('dept'):
			canvas_course_id_list_acct_term = (CourseInstance.objects.filter(canvas_course_id__isnull=False,
			                                                                 term=term,
			                                                                 course__department=account_sis_id.removeprefix('dept:'))
			                                   .values_list('canvas_course_id', flat=True)).distinct()
		else:
			canvas_course_id_list_acct_term = (CourseInstance.objects.filter(canvas_course_id__isnull=False,
			                                                                 term=term,
			                                                                 course__course_group=account_sis_id.removeprefix('coursegroup:'))
			                                   .values_list('canvas_course_id', flat=True)).distinct()

		# Create job details from unpublished courses list
		job_details_list = _create_job_details(job=job, course_id_list=canvas_course_id_list_acct_term)

		# Send job to queueing lambda
		utils.send_job_to_queueing_lambda(job_id, job_details_list, setting_to_be_modified, desired_setting)

		return response

	def get_success_url(self):
		"""
		If the submitted form is valid and was saved, build the url that is used in the redirect to the job listing page
		Check if the resource_link_id is already in the url, otherwise you may get a duplicate resource_link_id,
		depending on the environment you are in
		"""
		url = reverse('bulk_course_settings:job_list')
		if 'resource_link_id' not in url:
			url += '?resource_link_id=' + self.request.GET['resource_link_id']
		return url


class BulkSettingsRevertView(LTIPermissionRequiredMixin, LoginRequiredMixin, View):
	"""Endpoint used in reverting the given Job for the given school"""
	permission = 'bulk_course_settings'

	def get(self, request, school_id, job_id):
		job_has_already_been_reverted = Job.objects.filter(related_job_id=job_id)
		if job_has_already_been_reverted:
			logger.info('Job {} has already been reverted.'.format(job_id))
			messages.error(request, 'Job has already been reverted.')
		else:
			related_bulk_job = Job.objects.get(id=job_id)
			setting_to_be_modified = related_bulk_job.setting_to_be_modified

			reverse_desired_setting_mapping = {
				'False': 'True',
				'True': 'False'
			}

			desired_setting = reverse_desired_setting_mapping[related_bulk_job.desired_setting]

			new_bulk_job = Job.objects.create(related_job_id=related_bulk_job.id,
			                                  school_id=school_id,
			                                  term_id=related_bulk_job.term_id,
			                                  meta_term_id=related_bulk_job.meta_term_id,
			                                  setting_to_be_modified=setting_to_be_modified,
			                                  desired_setting=desired_setting,
			                                  created_by=str(self.request.user))

			new_bulk_job.workflow_status = constants.QUEUED
			new_bulk_job.save()

			related_job_details_course_id_list = (Details.objects.filter(parent_job=related_bulk_job.id).
			                                      exclude(workflow_status=constants.SKIPPED).
			                                      values_list('canvas_course_id', flat=True))

			job_details_list = _create_job_details(job=new_bulk_job, course_id_list=related_job_details_course_id_list)

			utils.send_job_to_queueing_lambda(new_bulk_job.id, job_details_list, setting_to_be_modified, desired_setting)

			# logger.info('Queued reversion job {} for related job {}'.format(new_bulk_job.id, related_bulk_job.id))
			messages.success(request, 'Reversion job was created successfully.')

		url = reverse('bulk_course_settings:job_list')
		if 'resource_link_id' not in url:
			url += '?resource_link_id=' + self.request.GET['resource_link_id']

		return redirect(url)


class BulkSettingsDetailView(LTIPermissionRequiredMixin, LoginRequiredMixin, ListView):
	"""Display information regarding the given Job and its Details"""
	model = Job
	template_name = 'bulk_course_settings/job_detail.html'
	context_object_name = 'job'
	permission = 'bulk_course_settings'

	def get_queryset(self):
		job_queryset = Job.objects.filter(id=self.kwargs['job_id'])

		# Annotate the Job queryset with counts for each workflow_state
		job_queryset = job_queryset.annotate(
			details_total_count=Count('details'),
			details_success_count=Count('details', filter=Q(details__workflow_status='COMPLETED')),
			details_failed_count=Count('details', filter=Q(details__workflow_status='FAILED')),
			details_skipped_count=Count('details', filter=Q(details__workflow_status='SKIPPED'))
		)

		return job_queryset[0]

	def get_context_data(self, **kwargs):
		context = super(BulkSettingsDetailView, self).get_context_data(**kwargs)
		original_job_id = self.kwargs['job_id']
		reversion_job = Job.objects.filter(related_job_id=original_job_id).first()
		context['reversion_job'] = reversion_job

		return context


def _create_job_details(job: Job, course_id_list: List[int]) -> List[Dict]:
	job_details_list = []

	# Create Details objects to efficiently insert all objects into the database in a single query.
	job_details_objects = [Details(parent_job_id=job.id, canvas_course_id=course_id) for course_id in course_id_list]

bulk_course_settings/templates/bulk_course_settings/create_new_job.html
{% extends 'bulk_course_settings/base.html' %}

{% block breadcrumb %}
    <a href="{% url 'dashboard_account' %}">Admin Console</a>
    <small><i class="fa fa-chevron-right"></i></small>
    Bulk Course Settings
{% endblock breadcrumb %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <h3 style="padding-bottom: 2em">Create a new bulk course settings job</h3>
        </div>
        <form action="" method="post">{% csrf_token %}
            <div class="row">
                <div class="col-sm-4">
                    <strong>Term: </strong>
                    <select name="term_id" id="id_term_id" class="form-control">
                        {% for term  in terms %}
                            <option value="{{ term.id }}">{{term.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-4">
                    <strong>Setting to change: </strong> {{ form.setting_to_be_modified }}
                </div>
                <div class="col-sm-4">
                    <strong>Target value: </strong> {{ form.desired_setting }}
                </div>
            </div>
            <input type="hidden" name="school_id" value="{{ school_id }}" />
            <div class="row" style="padding-top: 1em">
                <div class="col-sm-12">
                    <button type="button" ng-cloak class="btn btn-primary" id="bsc-create-btn" data-bs-toggle="modal" data-bs-target="#confirmCreate">Submit</button>
                    <a href="{% url 'bulk_course_settings:job_list' %}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </form>
        
        <!-- Confirmation Modal -->
        <div class="modal fade" id="confirmCreate" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Confirm Bulk Course Settings Job Creation</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <span id="modal-body-text"></span>
                        You are about to create a Bulk Course Settings job. It may take up to a minute to process. <br>
                        Are you sure you would like to proceed?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary" id="confirmCreateButton">Yes</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            document.getElementById('confirmCreateButton').addEventListener('click', function () {
                // Disable the "Yes" button and display loading spinner
                this.disabled = true;
                this.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...';
                
                // Submit the form
                document.querySelector('form').submit();
            });
        </script>
{% endblock content %}

bulk_course_settings/templates/bulk_course_settings/job_detail.html
{% extends 'bulk_course_settings/base.html' %}

{% block breadcrumb %}
    <a href="{% url 'dashboard_account' %}">Admin Console</a>
    <small><i class="fa fa-chevron-right"></i></small>
    <a href="{% url 'bulk_course_settings:job_list' %}">Bulk Course Settings</a>
{% endblock breadcrumb %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <h4>Details for Job ID: {{ job.id }}</h4>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <table class="table table-condensed">
                    <tr><th>Setting: </th><td>{{ job.setting_to_be_modified }}</td></tr>
                    <tr><th>Target Value: </th><td>{{ job.desired_setting }}</td></tr>
                    <tr><th>Created at: </th><td>{{ job.created_at }}</td></tr>
                    <tr><th>Status: </th><td>{{ job.get_workflow_status_display }}</td></tr>
                </table>
            </div>
            <div class="col-sm-6">
                <table class="table table-condensed">
                    <tr><th>Term: </th><td>{{ job.get_term_name }}</td></tr>
                    <tr><th>Total courses processed: </th><td>{{ job.details_total_count}}</td></tr>
                    <tr><th>Courses successfully updated: </th><td>{{ job.details_success_count }}</td></tr>
                    <tr><th>Skipped courses: </th><td>{{ job.details_skipped_count }}</td></tr>
                    <tr><th>Course update failures: </th><td>{{ job.details_failed_count }}</td></tr>
                </table>
            </div>
            <div class="row">
                <div class="col-sm-10">
                    {% if reversion_job %}
                        <div class="alert alert-info" role="alert">
                            <i>This job has already been reverted and cannot be reverted again.</i>
                        </div>
                    {% elif job.related_job_id %}
                        <div class="alert alert-info" role="alert">
                             <a href="{% url 'bulk_course_settings:job_detail' job_id=job.related_job_id %}"><i>This job is a reversion of job {{ job.related_job_id }} and cannot itself be reverted.</i></a>
                        </div>
                    {% elif job.workflow_status == 'COMPLETED_SUCCESS' and job.details_total_count == 0 %}
                        <div class="alert alert-info" role="alert">
                            <i>There are no settings to be reverted because no courses were updated.</i>
                        </div>
                    {% elif job.workflow_status == 'COMPLETED_SUCCESS' and job.details_total_count == job.details_skipped_count %}
                        <div class="alert alert-info" role="alert">
                            <i>There are no settings to be reverted because all courses were skipped.</i>
                        </div>
                    {% elif job.workflow_status == 'NEW' or job.workflow_status == 'QUEUED' or job.workflow_status == 'IN_PROGRESS' %}
                        <div class="alert alert-info" role="alert">
                            <i>This job is still in progress and cannot be reverted until it is complete.</i>
                        </div>
                    {% endif %}
                </div>
                <div class="col-sm-2">
                    {% if job.related_job_id is None and job.workflow_status == 'COMPLETED_SUCCESS' and not reversion_job and job.details_total_count > 0 and job.details_total_count != job.details_skipped_count %}
                        <a href="{% url 'bulk_course_settings:revert_setting' job.school_id job.id %}" class="btn btn-primary pull-right">Revert Job</a>
                    {% else %}
                        <a class="btn btn-default disabled pull-right">Revert Job</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-sm-12">
                    <h3>Courses processed by this job</h3>
                </div>
            </div>
            <div class="row" style="margin-top: 3em;">
                <div class="col-sm-12">
                    <table class="datatable table table-striped table-bordered dataTable no-footer" id="details_table">
                        <thead>
                            <th>Canvas Course ID</th>
                            <th>Status</th>
                            <th>Prior Value</th>
                        </thead>
                        <tbody>
                        {% for detail in job.details.all %}
                            <tr>
                                <td>{{ detail.canvas_course_id }}</td>
                                <td>{{ detail.get_workflow_status_display }}</td>
                                <td>{{ detail.current_setting_value }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $('#details_table').dataTable( {
                aaSorting: [[0, 'desc']],
                "oLanguage": {
                    "sSearch": "Search"
                }
            });

            $('[data-toggle="tooltip"]').tooltip();

        });
    </script>
{% endblock javascript %}

bulk_course_settings/templates/bulk_course_settings/job_list.html
{% extends 'bulk_course_settings/base.html' %}

{% block breadcrumb %}
    <a href="{% url 'dashboard_account' %}">Admin Console</a>
    <small><i class="fa fa-chevron-right"></i></small>
    Bulk Course Settings
{% endblock breadcrumb %}

{% block content %}
    <div class="container-fluid">
        <h4 class="mt-4">
            Bulk Course Settings Jobs:
            <a href="{% url 'bulk_course_settings:job_list' %}" class="btn btn-primary float-end ms-2" role="button"
                aria-pressed="true" aria-label="refresh page" title="Refresh page" data-bs-toggle="tooltip"
                data-bs-placement="top" data-bs-title="Refresh page"><i class="fa-solid fa-rotate-right"></i>
            </a>
            <a href="{% url 'bulk_course_settings:create_new_job' %}" class="btn btn-primary" style="float: right;">New Job</a>
        </h4>
        <div class="row" style="margin-top: .25em;">
            <table class="datatable table display no-footer">
                <thead>
                    <th>Job ID</th>
                    <th>Created</th>
                    <th>Term</th>
                    <th>Setting Modified</th>
                    <th>Desired Setting</th>
                    <th>Status</th>
                    <th>Total</th>
                    <th>Updated</th>
                    <th>Skipped</th>
                    <th>Failed</th>
                </thead>
                <tbody>
                {% for job in jobs %}
                    <tr>
                        <td><a href="{% url 'bulk_course_settings:job_detail' job_id=job.id %}"> {{ job.id }} </a> </td>
                        <td>{{ job.created_at }}</td>
                        {% if job.term_name %}
                            <td>{{ job.term_name }}</td>
                        {% else %}
                            <td>{{ job.get_term_name }}</td>
                        {% endif %}
                        <td>{{ job.get_setting_to_be_modified_display }}</td>
                        <td>
                            {% if job.related_job_id is None %}
                                {{ job.get_desired_setting_display }}
                            {% else %}
                                <a href="{% url 'bulk_course_settings:job_detail' job_id=job.related_job_id %}"> <i>reversion of job {{ job.related_job_id }}</i> </a>
                            {% endif %}
                        </td>
                        <td>{{ job.get_workflow_status_display }}</td>
                        <td>{{ job.details_total_count}}</td>
                        <td>{{ job.details_success_count }}</td>
                        <td>{{ job.details_skipped_count }}</td>
                        <td>{{ job.details_failed_count }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>
		$(document).ready(function() {
			$('.datatable').dataTable( {
				aaSorting: [[0, 'desc']],
				"aoColumnDefs": [ {
					'bSortable': false,
					'aTargets': [3] } ],
				"oLanguage": {
                  "sSearch": "Search"
                }
			});

      $('[data-toggle="tooltip"]').tooltip();

		});
	</script>
{% endblock javascript %}