icommons_tools/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^icommons_ui/', include('icommons_ui.urls')),
    url(r'^canvas_whitelist/', include('canvas_whitelist.urls', namespace="cwl")),
    url(r'^course_conclusion/', include('course_conclusion.urls', namespace='cc')),
    url(r'^course_selection/', include('course_selection.urls', namespace="cs")),
    url(r'^isites_export/', include('isites_export_tool.urls', namespace="et")),
    url(r'^not_authorized/', 'icommons_ui.views.not_authorized', name="not_authorized"),
    url(r'^pin/', include('icommons_common.auth.urls', namespace="pin")),
    url(r'^qualtrics_taker_auth/', include('qualtrics_taker_auth.urls', namespace="qta")),
    url(r'^qualtrics_whitelist/', include('qualtrics_whitelist.urls', namespace="qwl")),
    url(r'^shopping/', include('canvas_shopping.urls', namespace="sh")),
    url(r'^term_tool/', include('term_tool.urls', namespace="tt")),
]

qualtrics_whitelist/urls.py
from django.conf.urls import patterns, include, url

from qualtrics_whitelist import views
from qualtrics_whitelist.views import QualtricsAccessListView, QualtricsAccessSearchView, QualtricsAccessEditView, QualtricsAccessConfirmDeleteView, QualtricsAccessResultsListView

urlpatterns = patterns('',

    url(r'^$', QualtricsAccessListView.as_view(), name='qualtricsaccesslist'),

    url(r'^qualtrics_access_search/$', QualtricsAccessSearchView.as_view(), name='access_searchfor'),
    url(r'^qualtrics_access_update/$', views.access_update_person, name='access_update'),
    url(r'^qualtrics_access_confirmdelete/(?P<pk>\d+)/$', QualtricsAccessConfirmDeleteView.as_view(), name='access_confirmdelete'),
    url(r'^qualtrics_access_delete/$', views.delete, name='delete' ),
    url(r'^qualtrics_access_edit/(?P<pk>\d+)/$', QualtricsAccessEditView.as_view(), name='access_editview'),
    url(r'^qualtrics_access_results_list/$', QualtricsAccessResultsListView.as_view(), name='access_resultsview'),
    

)

term_tool/urls.py
from django.conf.urls import patterns, include, url

from term_tool.views import (
    ExcludeCoursesFromViewing,
    SchoolListView,
    TermCreateView,
    TermEditView,
    TermListView,
    exclude_courses,
)


urlpatterns = patterns('',
    url(r'^$', SchoolListView.as_view(), name='schoollist'),
    url(r'^(?P<school_id>\w+)/term_list/$', TermListView.as_view(),
        name='termlist'),
    url(r'^term/(?P<pk>\d+)/edit$', TermEditView.as_view(), name='termedit'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses$',
        exclude_courses, name='excludecourses'),
    url(r'^term/(?P<term_id>\d+)/(?P<school_id>\w+)/exclude_courses/data$',
        ExcludeCoursesFromViewing.as_view(), name='excludecoursesdata'),
    url(r'^term/new/(?P<school_id>\w+)$', TermCreateView.as_view(),
        name='termcreate'),

)

qualtrics_whitelist/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.contrib import messages
from icommons_common.models import *
from icommons_common.models import Person
from icommons_common.auth.views import LoginRequiredMixin
from icommons_common.auth.views import GroupMembershipRequiredMixin
from icommons_common.auth.decorators import group_membership_restriction
from django.contrib.auth.decorators import login_required
from django.conf import settings

import logging

logger = logging.getLogger(__name__)


@login_required
@group_membership_restriction(allowed_groups=settings.QUALTRICS_WHITELIST.get('allowed_groups', ''))
def delete(request):
    if request.method == 'POST':
        id_delete = request.POST.get('id')
        
        if 'cancel' in request.POST:
            logger.warning("Now canceling and returning")
        else:
            logger.debug('now deleting %s' % id_delete)
            delete_id = QualtricsAccessList.objects.get(id=id_delete).delete()
            logger.info('Whitelist delelte successful id delete: %s' % delete_id)
            messages.success(request, "Whitelist delete user successful")
    return HttpResponseRedirect(reverse('qwl:qualtricsaccesslist'))
    

@login_required
@group_membership_restriction(allowed_groups=settings.QUALTRICS_WHITELIST.get('allowed_groups', ''))
def access_update_person(request):
    logger.debug('trying to update now/////////')
    id_update = request.POST.get('id')
    if 'cancel' in request.POST:
        logger.warning("Now canceling")
    else:
        wlistSave = QualtricsAccessList()
        wlistSave.id = id_update
        logger.debug('Trying to update id :%s:' % id_update)
        user = request.POST.get('user_id')
        wlistSave.user_id = user
        test_description = request.POST.get('description')
        test_description = test_description.strip()
        # Verify the length and truncate to max length 255, if exceeds 255 chars
        # database max length for description is 255, but just need 150 for reason description
        if len(test_description) > 150:
            wlistSave.description = test_description[:150]
            messages.info(request, "The Reason Description is too long, it has been shorten to 150 characters.")
        else:
            wlistSave.description = test_description
        wlistSave.version = 0
        # Check the expiration_date date, if not "None", save to the database
        # if "None", save None to the database
        saveAs_expiration_date = request.POST.get('expiration_date')
       
        if saveAs_expiration_date == "None" or len(saveAs_expiration_date) == 0:
            wlistSave.expiration_date = None
        else:
            wlistSave.expiration_date = saveAs_expiration_date
       

        try:
            wlistSave.save()
            messages.success(request, "Whitelist update user successful")
        except IntegrityError, e:
            logger.error('Exception raised while saving to database:%s (%s)' % (e.args[0], type(e)))
            messages.error(request, "Whitelist update/deleted failed")

    return HttpResponseRedirect(reverse('qwl:qualtricsaccesslist'))


### Mixins:
### Class-based views:

class QualtricsAccessListView(GroupMembershipRequiredMixin, generic.ListView):
    allowed_groups = settings.QUALTRICS_WHITELIST.get('allowed_groups', '')
    model = QualtricsAccessList
    template_name = 'qualtrics_whitelist/qualtrics_access_list.html' 
    context_object_name = 'qualtrics_access_list'
    input_user_id = ""

    # override get_context to filter by name
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(QualtricsAccessListView, self).get_context_data(**kwargs)
        alist = []
        all_whitelist = QualtricsAccessList.objects.all()  # return all the objects from the WL table
        for wlobj in all_whitelist:
            alist.append(wlobj.user_id)

        personlist = Person.objects.filter(univ_id__in=alist)
        
        #print personlist.query  # print out SQL query

        for wlist in all_whitelist:
            for plist in personlist:
                if wlist.user_id == plist.univ_id:
                    wlist.name_first = plist.name_first
                    wlist.name_last = plist.name_last
                    wlist.email_address = plist.email_address
                    if plist.role_type_cd == 'XIDHOLDER':
                        wlist.role_type = 'XID'
                    else:
                        wlist.role_type = 'HUID'
                        break

        context['qualtrics_access_list'] = all_whitelist
        context['AUTHORIZEDTOEDIT'] = True

        return context      


class QualtricsAccessSearchView(GroupMembershipRequiredMixin, generic.TemplateView):
    allowed_groups = settings.QUALTRICS_WHITELIST.get('allowed_groups', '')
    template_name = 'qualtrics_whitelist/qualtrics_access_search.html'


class QualtricsAccessResultsListView(GroupMembershipRequiredMixin, generic.ListView):
    allowed_groups = settings.QUALTRICS_WHITELIST.get('allowed_groups', '')
    model = QualtricsAccessList
    template_name = 'qualtrics_whitelist/qualtrics_access_results_list.html'
    context_object_name = 'qualtrics_access_list'

    def post(self, request, *args, **kwargs):
        error_message = ""
        firstname = lastname = ""
        results_list = []
        results_dict = {}
        search_term = request.POST.get('user_search_term')
        if 'Search' in request.POST:
            search_term = search_term.strip()
            if "@" in search_term:
                # treat it as an email address     
                personlist = Person.objects.filter(email_address__iexact=search_term)

                if personlist:
                    # person found on ldap_people_plus_simple model
                    for plist in personlist:
                        input_user_id = plist.univ_id 

                        q = QualtricsAccessList.objects.all().filter(user_id=plist.univ_id)
                        if q:
                                
                            for qlist in q:
                                if plist.univ_id == qlist.user_id:
                                    qlist.on_list = True
                                else:
                                    qlist.on_list = False
                        else:
                            # exist on Person object, but not on whitelist database
                            qlist = QualtricsAccessList(user_id=plist.univ_id)
                            qlist.on_list = False

                        # display either HUID or XID as the Role Type in UI
                        if plist.role_type_cd == 'XIDHOLDER':
                            qlist.role_type = 'XID'
                        else:
                            qlist.role_type = 'HUID'

                        qlist.user_id = plist.univ_id
                        qlist.first_name = plist.name_first 
                        qlist.last_name = plist.name_last
                        qlist.email = plist.email_address

                        results_dict[qlist.user_id] = qlist
                            
                    return render(request, 'qualtrics_whitelist/qualtrics_access_results_list.html', 
                                      {'user_input': input_user_id, 'results_list': results_dict, 'error_message': "", })
                    
                else:
                    # person not found in Person database
                    logger.error('Email not found in Person database :%s:' % search_term)
                    return render(request, 'qualtrics_whitelist/qualtrics_access_results_list.html', 
                                  {'user_input': search_term, 'results_list': results_dict, 'error_message': "Person not found in the Harvard Directory", })


            else:
                # treat it as a user id
                if not len(search_term) <= 0:
                    alist = []
                    qlist = QualtricsAccessList.objects.all().filter(user_id=search_term)  # return all the objects from the WL table

                    if qlist:
                        # User already exist on whitelist
                        for wlobj in qlist:
                            alist.append(wlobj.user_id)

                        personlist = Person.objects.filter(univ_id__in=alist)                    
                        for wlist in qlist:
                            for plist in personlist:
                                if wlist.user_id == plist.univ_id:
                                    wlist.first_name = plist.name_first
                                    wlist.last_name = plist.name_last
                                    wlist.email = plist.email_address
                                    wlist.on_list = True
                                    if plist.role_type_cd == 'XIDHOLDER':
                                        wlist.role_type = 'XID'
                                    else:
                                        wlist.role_type = 'HUID'
                                    results_dict[wlist.user_id] = wlist
                    else:
                        # User is not on the whitelist
                        personlist = Person.objects.filter(univ_id=search_term)

                        for plist in personlist:
                            plist.user_id = plist.univ_id
                            plist.first_name = plist.name_first
                            plist.last_name = plist.name_last
                            plist.email = plist.email_address
                            plist.on_list = False
                            if plist.role_type_cd == 'XIDHOLDER':
                                plist.role_type = 'XID'
                            else:

qualtrics_whitelist/templates/qualtrics_whitelist/base.html
{% extends "icommons_ui/base_datatables.html" %}

{% block tool_title %}Qualtrics Whitelist{% endblock %}

qualtrics_whitelist/templates/qualtrics_whitelist/qualtrics_access_confirmdelete.html
{% extends "qualtrics_whitelist/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}Confirm a delete{% endblock %}
{% block pagetitle %}Confirm a delete{% endblock %}


{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class="form-horizontal" action="{% url 'qwl:delete' %}" method="POST">{% csrf_token %}
	<p>Are you sure you want to delete this record?</p><br/>
	
	<div class="form-group">
    	<label for="inputHUID" class="col-sm-2 control-label">HUID</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.user_id }}</p>
    	</div>
    </div>
    	<div class="form-group">
    	<label for="inputFirstName" class="col-sm-2 control-label">First Name</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.first_name }}</p>
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputLastName" class="col-sm-2 control-label">Last Name</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.last_name }}</p>
    	</div>
    </div>
	<div class="form-group">
    	<label for="inputEmail" class="col-sm-2 control-label">Email</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.email_address }}</p>
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputDescription" class="col-sm-2 control-label">Reason for Access</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.description }}</p>
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputExpirationDate" class="col-sm-2 control-label">Access End Date</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.expiration_date }}</p>
    	</div>
    </div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<input type="hidden" name="id" value="{{ object.id }}" >
			<button type="submit" class="btn btn-primary" name="confirm">Confirm</button>
			<button type="submit" class="btn btn-link" name="cancel">Cancel</button>
		</div>
	</div>

</form>

{% endblock %}

qualtrics_whitelist/templates/qualtrics_whitelist/qualtrics_access_edit.html
{% extends "qualtrics_whitelist/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}Edit a Person{% endblock %}
{% block pagetitle %}Edit Person{% endblock %}


{% block content %}
<h4>Update the reason and/or the access end date</h4>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class="form-horizontal" name="form1" action="{% url 'qwl:access_update' %}" method="POST">{% csrf_token %}
<input type="hidden" name="id" value="{{ object.id }}" >
<input type="hidden" name="user_id" value="{{ object.user_id }}" >
<div class="form-group">
    	<label for="inputHUID" class="col-sm-2 control-label">HUID</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.user_id }}</p>
    	</div>
    </div>
    	<div class="form-group">
    	<label for="inputFirstName" class="col-sm-2 control-label">First Name</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.first_name }}</p>
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputLastName" class="col-sm-2 control-label">Last Name</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.last_name }}</p>
    	</div>
    </div>
	<div class="form-group">
    	<label for="inputEmail" class="col-sm-2 control-label">Email</label>
    	<div class="col-sm-10">
    		<p class="form-control-static">{{ object.email_address }}</p>
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputDescription" class="col-sm-2 control-label">Reason for Access</label>
    	<div class="col-sm-10">
    		<input type="text" class="form-control" name="description"   value="{{ object.description }}">
    	</div>
    </div>
    <div class="form-group">
    	<label for="inputExpirationDate" class="col-sm-2 control-label">Access End Date</label>
    	<div class="col-sm-10">
    		<input type="text" class="dateinput" name="expiration_date"  value="{{ object.expiration_date | date:"Y-m-d" }}">
    	</div>
    </div>
    <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
    		<button type="submit" class="btn btn-primary" name="Update" onclick="return checkReason()" >Update</button>
    		<button type="submit" class="btn btn-link" name="cancel">Cancel</button>
    	</div>
    </div>
</form>


{% endblock %}

{% block javascript %}
{{ block.super }}
<script>

$(document).ready(function() { 
	$('.dateinput').datepicker({
        format: "yyyy-mm-dd"
    });
});

function checkReason()
{
	if (!form1.description.value)
	{
		alert ("Please Enter a Reason description.");
		return false;
	}
	return true;
}
	
</script>

{% endblock %}

qualtrics_whitelist/templates/qualtrics_whitelist/qualtrics_access_list.html
{% extends "qualtrics_whitelist/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}List of People{% endblock %}
{% block pagetitle %}List of People{% endblock %}


{% block content %}
{% if AUTHORIZEDTOEDIT %}
{% if qualtrics_access_list %}
<table class="datatable table table-striped table-bordered">
    <thead>
        <tr>
        	<th>Role Type</th>
            <th>HUID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email Address</th>
            <th>Access End Date</th>
            <th>Reason for Access</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
		{% for person in qualtrics_access_list %}

			<tr>
				<td>{{ person.role_type }}</td>
				<td>{{ person.user_id }}</td>
				<td>{{ person.name_first }}</td>
				<td>{{ person.name_last }}</td>
				<td>{{ person.email_address }}</td>
				<td>{{ person.expiration_date }}</td>
				<td>{{ person.description }}</td>
				<td>
					<a href="{% url 'qwl:access_editview' person.id %}">Update</a>
					<a href="{% url 'qwl:access_confirmdelete' person.id %}">Delete</a>
				</td>
			</tr>

		{% endfor %}
	<tbody>
</table>

{% endif %}

<a href="{% url 'qwl:access_searchfor' %}" class="btn btn-primary">Add a Person</a>

{% endif %}

{% endblock %}

{% block javascript %}
{{ block.super }}
	<script>
		$(document).ready(function() { 
			$('.datatable').dataTable( {
				aaSorting: [[0, 'asc']],
				"aoColumnDefs": [ { 
					'bSortable': false, 
					'aTargets': [ 6 ] } ],
				"oLanguage": {
                  "sSearch": "Search"
                }
			});
		});
	</script>

{% endblock %}

qualtrics_whitelist/templates/qualtrics_whitelist/qualtrics_access_results_list.html
{% extends "qualtrics_whitelist/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}Results List{% endblock %}
{% block pagetitle %}Results List{% endblock %}


{% block content %}
<h4>Choose one or more and enter the reason and access end date, if necessary</h4>


<form class="form-horizontal" name="form1" id="checkboxForm" action="./" method="POST">{% csrf_token %}
<input type="hidden" name="user_id" value="{{ user_input }}" >
<input type="hidden" name="users_list" value="{{ results_list }}" >

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table border="2">
	<thead>
        <tr>
        	<th></th>
            <th>Role Type</th>
            <th>HUID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
    {% if results_list %}
		{% for key, value in results_list.items %}
	 		<tr>
			{% if value.on_list %}
				<td><input type="checkbox" checked disabled></td>		
			{% else %}	
				<td><input type="checkbox" name="user_check_list" id="checkbox" value="{{value.user_id}}" class="checkbox"></td>
			{% endif %}
				<td>{{ value.role_type }}</td>
				<td>{{ value.user_id }}</td>
				<td>{{ value.first_name }}</td>
				<td>{{ value.last_name }}</td>
				<td>{{ value.email }}</td>
			</tr> 
		{% endfor %}
	{% endif %}
	<tbody>
</table>
<br>
<div class="form-group">
	<label class="col-sm-2 control-label">Reason for Access</label>
	<div class="col-sm-10">
    	<input type="text" class="form-control" name="description"  placeholder="Enter reason for access">
    </div>
</div>
<div class="form-group">
	<label class="col-sm-2 control-label">Access End Date</label>
	<div class="col-sm-10">
    	<input type="text" class="dateinput" name="expiration_date"  placeholder="Enter access end date">
    </div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button id="sub" class="btn btn-primary" type="submit" onclick="return checkReason()"  name="Save" disabled="disabled" >Save</button>
		<button class="btn btn-link" type="submit" name="Cancel">Cancel</button>
	</div>
</div>
</form>
<h6>Reminder: In Qualtrics, please update User Type and Division manually for contractors/POIs with HUIDs beginning with “01” or “02” as they could be granted access with Generic user type and Other division.</h6>

{% endblock %}


{% block javascript %}
{{ block.super }}
<script>

$(document).ready(function() { 
	$('.dateinput').datepicker({
		format: "yyyy-mm-dd",
		startDate: "today"
	});
});

$('.checkbox').change(function() {
    if ($('.checkbox:checked').length) {
        $('#sub').removeAttr('disabled');
    } else {
        $('#sub').attr('disabled', 'disabled');
    }
});


function checkReason()
{
	if (!form1.description.value)
	{
		alert ("Please Enter a reason for access.");
		return false;
	}
	return true;
}
	
</script>

{% endblock %}

qualtrics_whitelist/templates/qualtrics_whitelist/qualtrics_access_search.html
{% extends "qualtrics_whitelist/base.html" %}
{% load crispy_forms_tags %}
{% load static %}



{% block content %}

<h2>Add a user to the Qualtrics Whitelist</h2>

<form class="form-inline" method="POST" action="{% url 'qwl:access_resultsview' %}">{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class="form-group">
		<label class="sr-only" for="user_search_term">Email Address or user ID</label>
	<input type="search" name="user_search_term" class="form-control" id="user_search_term" placeholder="Enter email or HUID"/>
	</div>
	<button type="submit" name="Search" id="user_search_button" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Searching...">
	<i class="fa fa-search"></i> Search</button>
	<a href="{% url 'qwl:qualtricsaccesslist' %}">Cancel</a>
</form>


{% endblock %}